Bootstrap: docker
From: ubuntu:18.04

%help
	Tensorflow 2.1.0 container	

%files
	Anaconda3-2020.02-Linux-x86_64.sh /downloads/

%post
	apt update
	apt install -y libgl1-mesa-dev \
		vim
	bash /downloads/Anaconda3-2020.02-Linux-x86_64.sh \
		-b \
		-p /usr/local \
		-f 
	conda create -y -n tf \
		&& . /usr/local/etc/profile.d/conda.sh \
		&& conda activate tf \
	        && conda install -y -c anaconda tensorflow=2.1.0 \
		&& conda install -y -c conda-forge opencv \
		&& conda install -y -c conda-forge scipy \
	        && conda install -y -c conda-forge matplotlib \
	        && conda install -y -c conda-forge notebook \
	        && conda install -y -c conda-forge jupyter \
	        && conda install -y -c conda-forge pydicom \
	        && conda install -y -c conda-forge pillow \
		&& conda install -y -c conda-forge scikit-learn \
		&& conda install -y -c anaconda pandas 
	rm -rf /download
	apt clean
	echo ". /usr/local/etc/profile.d/conda.sh" >> $SINGULARITY_ENVIRONMENT
%runscript
	. /usr/local/etc/profile.d/conda.sh
	conda activate tf
	exec /bin/bash "$@"
